slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint
    scan_topic: /scan
    use_sim_time: true
    mode: mapping 

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05
    map_update_interval: 1.0        
    resolution: 0.05
    
    use_scan_matching: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1  
    scan_buffer_size: 10
    
    correlation_search_space_dimension: 0.5 
    correlation_search_space_resolution: 0.01

    do_loop_closing: true
    loop_search_space_dimension: 8.0       
    loop_match_minimum_chain_size: 3      
    loop_match_maximum_variance_coarse: 3.0 
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45